version: '3.7'
services:
  db:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - db_network
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opendsa
      MYSQL_DATABASE: opendsa
      MYSQL_USER: opendsa
      MYSQL_PASSWORD: opendsa

  opendsa-lti:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
    image: opendsa-lti:latest
    volumes:
      - .:/opendsa-lti
    entrypoint: /opendsa-lti/docker-entrypoint.sh
    command: ["./scripts/start.sh"]
    networks:
      - db_network
    ports:
      - "8080:80"
    depends_on:
      - db

networks:
  db_network:
    driver: bridge
volumes:
  db:
