# can account for multiple environments, if we wanted to use diff env for specs being worked on
# based on openlrw - would most likely be diff config for other stores
defaults: &defaults
  enabled: false
  base_url: 'http://localhost:9966/'
  api_username: api_username
  api_password: api_password
evelopment:
  <<: *defaults

test:
  enabled: true
  base_url: 'http://localhost:9966/'
  api_username: api_username
  api_password: api_password

production:
  <<: *defaults